# Form implementation generated from reading ui file 'manager_windoww.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
import sys
import os
from PyQt6 import QtWidgets ,QtGui, QtCore
from PyQt6.QtGui import QPixmap

# ========== ЭТА ФУНКЦИЯ ОБЯЗАТЕЛЬНА ДЛЯ КАРТИНОК В EXE ==========
def resource_path(relative_path):
    """Получить путь к файлу, работающий и в .py, и в .exe"""
    try:
        # PyInstaller создаёт временную папку и хранит путь в _MEIPASS
        base_path = sys._MEIPASS
    except Exception:
        # Если запущено как скрипт (не exe)
        base_path = os.path.abspath(".")
    return os.path.join(base_path, relative_path)
class Ui_Form_manager(object):


    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 800)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        Form.setFont(font)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_3 = QtWidgets.QFrame(parent=Form)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(parent=self.frame_3)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(10, 0, 151, 81))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setPixmap(QPixmap(resource_path("Icon.png")))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_name = QtWidgets.QLabel(parent=self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_name.setFont(font)
        self.label_name.setText("")
        self.label_name.setObjectName("label_name")
        self.verticalLayout.addWidget(self.label_name)
        self.label_name_2 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_name_2.setText("")
        self.label_name_2.setObjectName("label_name_2")
        self.verticalLayout.addWidget(self.label_name_2)
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame_5 = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_nazad = QtWidgets.QPushButton(parent=self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pushButton_nazad.setFont(font)
        self.pushButton_nazad.setStyleSheet("background-color: #7FFF00;")
        self.pushButton_nazad.setObjectName("pushButton_nazad")
        self.verticalLayout_2.addWidget(self.pushButton_nazad)
        self.horizontalLayout.addWidget(self.frame_5)
        self.pushButton_zakazi = QtWidgets.QPushButton(parent=self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pushButton_zakazi.setFont(font)
        self.pushButton_zakazi.setStyleSheet("background-color: #7FFF00;")
        self.pushButton_zakazi.setObjectName("pushButton_zakazi")
        self.horizontalLayout.addWidget(self.pushButton_zakazi)
        self.verticalLayout_5.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(parent=Form)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_sortirovka = QtWidgets.QLabel(parent=self.frame_4)
        self.label_sortirovka.setObjectName("label_sortirovka")
        self.horizontalLayout_2.addWidget(self.label_sortirovka)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.frame_4)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.label_4 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.comboBox_2 = QtWidgets.QComboBox(parent=self.frame_4)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_2)
        self.label_3 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.comboBox = QtWidgets.QComboBox(parent=self.frame_4)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.verticalLayout_5.addWidget(self.frame_4)
        self.scrollArea = QtWidgets.QScrollArea(parent=Form)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 976, 609))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_5.addWidget(self.scrollArea)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Окно Менеджера"))
        self.pushButton_nazad.setText(_translate("Form", "На главное окно"))
        self.pushButton_zakazi.setText(_translate("Form", "Заказы"))
        self.label_sortirovka.setText(_translate("Form", "Поиск : "))
        self.label_4.setText(_translate("Form", "Сортировать : "))
        self.comboBox_2.setItemText(0, _translate("Form", "По умолчанию"))
        self.comboBox_2.setItemText(1, _translate("Form", "По возрастанию"))
        self.comboBox_2.setItemText(2, _translate("Form", "По убыванию"))
        self.label_3.setText(_translate("Form", "Поставщик:"))
        self.comboBox.setItemText(0, _translate("Form", "Все"))
        self.comboBox.setItemText(1, _translate("Form", "Kari"))
        self.comboBox.setItemText(2, _translate("Form", "Обувь для вас"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form_manager()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
